# ===================================
# CONEXIÓN A BASE DE DATOS POSTGRESQL
# ===================================
spring.datasource.url=jdbc:postgresql://localhost:5432/deportes_db
spring.datasource.username=postgres
spring.datasource.password=050510
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================
# 'validate': Hibernate solo verifica que tus tablas manuales coincidan con las clases @Entity.
# Si algo no coincide, te avisará al arrancar sin alterar la base de datos.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect